;; -*- lexical-binding: t; -*-

(defvar init-pkgs t)

(setopt init-pkgs nil)
(require 'definitions)
(require 'pkgs-setup)
(require 'basic-setup)
(require 'theme-setup)
(require 'font-setup)
(require 'editor-setup)
(require 'ui-setup)
(require 'icons-setup)
(require 'org-setup)
(require 'languages-setup)
(require 'treesitter-setup)
(require 'lsp-setup)
(require 'hooks-setup)
(require 'dashboard-setup)
(require 'keybinds-setup)
(require 'font-lock-setup)