;; -*- lexical-binding: t; -*-
(require 'eglot)
(require 'treesit)

;; language modes
(autoload 'hyprlang-ts-mode "hyprlang-ts-mode")
;; (autoload 'just-ts-mode "just-ts-mode")
;; (autoload 'zig-ts-mode "zig-ts-mode")
;; (autoload 'nix-ts-mode "nix-ts-mode")
;; (autoload 'v-mode "v-mode")
;; (autoload 'markdown-mode "markdown-mode")
;; (autoload 'fish-mode "fish-mode")
;; (autoload 'ini-mode "ini-mode")

(setq-default treesit-language-source-alist
 '((hyprlang    "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
   (c           "https://github.com/tree-sitter/tree-sitter-c")
   (cpp         "https://github.com/tree-sitter/tree-sitter-cpp")
   (bash        "https://github.com/tree-sitter/tree-sitter-bash")
   (cmake       "https://github.com/uyha/tree-sitter-cmake")
   (css         "https://github.com/tree-sitter/tree-sitter-css")
   (go          "https://github.com/tree-sitter/tree-sitter-go")
   (nix         "https://github.com/nix-community/tree-sitter-nix")
   (rust        "https://github.com/tree-sitter/tree-sitter-rust")
   (javascript  "https://github.com/tree-sitter/tree-sitter-javascript")
   (json        "https://github.com/tree-sitter/tree-sitter-json")
   (python      "https://github.com/tree-sitter/tree-sitter-python")
   (toml        "https://github.com/tree-sitter/tree-sitter-toml")
   (yaml        "https://github.com/ikatyang/tree-sitter-yaml")
   (just        "https://github.com/indianboy42/tree-sitter-just")
   (lua         "https://github.com/tjdevries/tree-sitter-lua")
   (zig         "https://github.com/maxxnino/tree-sitter-zig")))

;; lsp servers
(setq-default eglot-server-programs
 '((python-ts-mode   . ("pylsp"))
   (fish-mode        . ("fish-lsp" "start"))
   (markdown-mode    . ("marksman" "server"))
   (json-ts-mode     . ("vscode-json-language-server" "--stdio"))
   (css-ts-mode      . ("vscode-css-language-server" "--stdio"))
   (js-ts-mode       . ("vscode-eslint-language-server" "--stdio"))
   (yaml-ts-mode     . ("yaml-language-server" "--stdio")) 
   (v-mode           . ("~/.config/v-analyzer/bin/v-analyzer" "--stdio"))
   (rust-ts-mode     . ("rust-analyzer"))))

;; mode association
(setq auto-mode-alist (append
  '(("\\.toml\\'"          . toml-ts-mode)
    ("\\.c\\'"             . c-ts-mode)
    ("\\.C\\'"             . c-ts-mode)
    ("\\.h\\'"             . c-ts-mode)
    ("\\.H\\'"             . c-ts-mode)
    ("\\.cpp\\'"           . c++-ts-mode)
    ("\\.cxx\\'"           . c++-ts-mode)
    ("\\.hpp\\'"           . c++-ts-mode)
    ("\\.hxx\\'"           . c++-ts-mode)
    ("\\.ts\\'"            . typescript-ts-mode)
    ("\\.tsx\\'"           . typescript-ts-mode)
    ("\\.go\\'"            . go-ts-mode)
    ("\\go.mod\\'"         . go-mod-ts-mode)
    ("\\.js\\'"            . js-ts-mode)
    ("\\.jsx\\'"           . js-ts-mode)
    ("\\.css\\'"           . css-ts-mode)
    ("\\.sh\\'"            . bash-ts-mode)
    ("\\.bash\\'"          . bash-ts-mode)
    ("\\.java\\'"          . java-ts-mode)
    ("\\.class\\'"         . java-ts-mode)
    ("\\.json\\'"          . json-ts-mode)
    ("\\.jsonc\\'"         . json-ts-mode)
    ("\\.rb\\'"            . ruby-ts-mode)
    ("\\.rs\\'"            . rust-ts-mode)
    ("\\.yaml\\'"          . yaml-ts-mode)
    ("\\.yml\\'"           . yaml-ts-mode)
    ("\\CMakeList.txt\\'"  . cmake-ts-mode)
    ("\\.cmake\\'"         . cmake-ts-mode)
    ("\\.py\\'"            . python-ts-mode)
    ("\\.pyc\\'"           . python-ts-mode)
    ("\\.pyi\\'"           . python-ts-mode)
    ("\\.pyd\\'"           . python-ts-mode)
    ("\\.pyo\\'"           . python-ts-mode)
    ("\\.pyw\\'"           . python-ts-mode)
    ("\\.pyz\\'"           . python-ts-mode)
    ("\\.lua\\'"           . lua-ts-mode)
    ("\\fonts.conf\\'"     . conf-mode-maybe) 
    ("\\gitignore\\'"      . conf-mode)
    ("\\gitattributes\\'"  . conf-mode)
    ("\\.conf\\'"          . conf-mode)
    ("\\.desktop\\'"       . conf-desktop-mode)
    ("\\.service\\'"       . conf-desktop-mode)
    ("\\hyprland.conf\\'"  . hyprlang-ts-mode)
    ("\\hyprlock.conf\\'"  . hyprlang-ts-mode)
    ("\\hyprpaper.conf\\'" . hyprlang-ts-mode)
    ("\\.md\\'"            . markdown-mode)
    ("\\.MD\\'"            . markdown-mode)
    ("\\.mkdn\\'"          . markdown-mode)
    ("\\.markdown\\'"      . markdown-mode)
    ("\\.nix\\'"           . nix-ts-mode)
    ("\\.fish\\'"          . fish-mode)
    ("\\fish_variables\\'" . fish-mode)
    ("\\.zig\\'"           . zig-ts-mode)
    ("\\.zig.zon\\'"       . zig-ts-mode)
    ("\\justfile\\'"       . just-ts-mode)
    ("\\.v\\'"             . v-mode)
    ("\\.vsh\\'"           . v-mode)
    ("\\v.mod\\'"          . v-mode)
    ("\\.ini\\'"           . ini-mode))
  auto-mode-alist))

(provide 'languages)
